backend/.gitignore
=> refactor : 서버 설정 변경

backend/src/main/java/wap/dingdong/backend/BackendApplication.java, backend/src/main/java/wap/dingdong/backend/domain/Buy.java, backend/src/main/java/wap/dingdong/backend/domain/Comment.java, backend/src/main/java/wap/dingdong/backend/domain/Image.java, backend/src/main/java/wap/dingdong/backend/domain/Location.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/domain/ProductLike.java, backend/src/main/java/wap/dingdong/backend/domain/ProductLocation.java, backend/src/main/java/wap/dingdong/backend/domain/ProductStatus.java, backend/src/main/java/wap/dingdong/backend/domain/Sell.java, backend/src/main/java/wap/dingdong/backend/domain/User.java, backend/src/main/java/wap/dingdong/backend/domain/WishList.java, backend/src/main/resources/application.properties
상품 엔티티 100%, 나머지 엔티티는 설계만 구현 완료,
엔티티 클래스가 더 늘어날 수 있음
=> feature : 도메인1

backend/src/main/java/wap/dingdong/backend/domain/Buy.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/domain/Sell.java, backend/src/main/java/wap/dingdong/backend/domain/Wish.java, backend/src/main/resources/application.properties
=> refactor : 도메인 수정

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
메인페이지의 상품 리스트 조회 구현 완료
수정사항 : gitignore에 application.properties가 적용안되는걸 되게함 
미구현 : 검증, 예외처리
=> feature : 메인페이지 상품 리스트 조회

backend/src/test/java/wap/dingdong/backend/BackendApplicationTests.java
=> Revert "fix : 테스트코드"

backend/.gitignore, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/test/java/wap/dingdong/backend/BackendApplicationTests.java
=> fix : 버그수정

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Buy.java, backend/src/main/java/wap/dingdong/backend/domain/Comment.java, backend/src/main/java/wap/dingdong/backend/domain/Image.java, backend/src/main/java/wap/dingdong/backend/domain/Location.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/domain/Sell.java, backend/src/main/java/wap/dingdong/backend/domain/Wish.java, backend/src/main/java/wap/dingdong/backend/payload/ImageDto.java, backend/src/main/java/wap/dingdong/backend/payload/LocationDto.java, backend/src/main/java/wap/dingdong/backend/payload/request/ProductCreateRequest.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
**댓글작업이랑 코드 충돌날 수도 있으니까 main에 merge는 나중에 하는걸로**
1. api 명세 변경
프런트에서 처리하기 까다롭게 api명세가 작성된것 같아서 프런트에서 더 쉽게 처리할 수 있도록 명세를 바꾸고 이에따라 코드 변경
지역과 이미지의 value에 list만 넣은것이 아닌 지역과 이미지의 value에 list안에 json을 넣었음
2. setter 사용을 최소화하고 생성자방식 초기화를 사용하게 수정함
=> refactor : api명세 변경

backend/src/main/java/wap/dingdong/backend/config/SecurityConfig.java, backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Location.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/payload/request/ProductCreateRequest.java, backend/src/main/java/wap/dingdong/backend/payload/response/CommentResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
=> feature : 로그인 연동

backend/src/main/java/wap/dingdong/backend/controller/UserController.java, backend/src/main/java/wap/dingdong/backend/payload/response/UserResponse.java, backend/src/main/java/wap/dingdong/backend/service/UserService.java
GET/user/me : 현재 로그인된 유저의 정보를 가져옴
=> refactor : userme 수정

backend/src/main/java/wap/dingdong/backend/config/SecurityConfig.java, backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/repository/ProductRepository.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
일단 pr하지말것
1. GET/product 는 이제 로그인 검증 필요 없음
2. 페이지네이션으로 상품리스트 조회때 8개씩 최신순으로 반환하게함 
쿼리스트링 GET/product/list/recent?page={페이지번호} 로 조회 가능
기존에 모든 상품리스트를 응답하는 GET/product/list 도 일단은 남겨둠
=> feature : 페이지네이션

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/domain/ProductLike.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
- `POST` 메소드
- 헤더에서 key - `user_id` & value - `해당하는 회원의 식별자값(Integer)` 전달
- ex. key - `user_id` & value - `1`
=> Feature : 찜하기

backend/src/main/java/wap/dingdong/backend/domain/Comment.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/payload/CommentDto.java, backend/src/main/java/wap/dingdong/backend/payload/response/CommentResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductDetailResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
엔티티 저장하는 방식을 @CreateDate LocalDateTime 사용으로 통일
status (판매완료) 를 0 , 1 형식으로 바꿈 
찜목록 관련해서 수정해야할 부분이 있음 추후에 리팩토링 예정
=> refactor : 응답 수정

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
- 상품 찜하기 -> 상품 상태 변경하기 기능으로 수정
- 불필요한 코드 주석처리)
- status = 0 : 판매중
- status = 1 : 판매완료
- 한 번 클릭(POST)하면 status 값이 +1 되고, 다시 한 번 클릭하면 status 값이 -1 됨.
- 백엔드에서 상품을 게시한 사용자만 상품 상태를 변경할 수 있도록 처리하였음
- 프론트에서는 이를 바탕으로 GET /product/{productId} 로 상품 상세정보를 불러올 때, product의 status 값에 따라 프론트에서 달리 보이도록 구현해야 함
---------
Bearer {TOKEN}
```json
{
"email": "hyeonsian84@gmail.com",
"productId": 1,
"title": "충전기",
"price": 20000,
"contents": “충전기 설명입니다.",
"locations": [],
"status": 1, // 기본값(=0)에서 한 번 클릭(post)하면 +1 됨
"images": [],
"productLike": 0,
"createdAt": "2024-05-29T13:59:57.820426",
"comment": []
}
```
=> Feature: : 상품 상태 변경하기

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Image.java, backend/src/main/java/wap/dingdong/backend/payload/ImageDto.java, backend/src/main/java/wap/dingdong/backend/payload/request/ProductCreateRequest.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
=> Revert "base64방식 이미지 업로드"

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/domain/Image.java, backend/src/main/java/wap/dingdong/backend/domain/Product.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/main/java/wap/dingdong/backend/repository/ProductRepository.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java, backend/src/main/java/wap/dingdong/backend/util/AwsUtils.java
=> Feature/#101 검색

backend/src/main/java/wap/dingdong/backend/payload/CommentDto.java, backend/src/main/java/wap/dingdong/backend/payload/response/CommentResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductDetailResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java
=> refactor : 유저명 반환

backend/src/main/java/wap/dingdong/backend/payload/response/ProductDetailResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductInfoResponse.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductResponse.java
=> refactor : 유저id응답

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.css, frontend/src/Comment.js, frontend/src/Header.js, frontend/src/ProductDetail.js, frontend/src/ProductList.js, frontend/src/Productreg.js, frontend/src/index.js
> 상품상세페이지 `댓글기능추가` 및 `컴포넌트 위치` 조정
> 상품상세 페이지 `판매완료버튼 `클릭시 상품리스트에 `판매완료 라벨 `부착
> `상품 등록시간->한국시간`으로 변환
> 상품상세 페이지 `이미지 슬라이더` 구현 완료
=> Feature/#113 상품상세 댓글

backend/src/main/java/wap/dingdong/backend/controller/ProductController.java, backend/src/main/java/wap/dingdong/backend/payload/response/ProductsResponse.java, backend/src/main/java/wap/dingdong/backend/service/ProductService.java
페이지네이션 시 페이지 개수를 응답으로 추가 키명 : pageCount
=> feature : 페이지 개수 응답

frontend/src/App.js, frontend/src/Header.js, frontend/src/Mypage.js, frontend/src/ProductDetail.js, frontend/src/ProductEdit.js, frontend/src/ProductList.js, frontend/src/Productreg.js
=> refactor:검색
